#!/usr/bin/env bash

extip=$(dig +short myip.opendns.com @resolver1.opendns.com)

case $BLOCK_BUTTON in
    1)  notify-send $extip;;
esac

#echo -e "<span foreground='black' background='#01A252' font-style='italic'>$extip </span>\n"
if $extip ; then
    echo -e "<span foreground='red'></span>\n"
else
    echo -e "<span foreground='green'></span>\n"
fi
