#!/bin/bash
while [ "$select" != "NO" -a "$select" != "YES" ]; do
    select=$(echo -e 'NO\nYES' | dmenu -nb '#2f343f' -nf '#f3f4f5' -sb '#FF000B' -sf '#f3f4f5' -i -p "Are you sure you want to hybernate?")
    [ -z "$select" ] && exit 0
done
[ "$select" = "NO" ] && exit 0
systemctl hybrid-sleep
